### ISSUE TITLE
Bump the version

### ISSUE THREAD

**Issue by paskal** [pinkeen/docker-html-to-pdf#3]
Hi!

Thank you for great job, I'm [using](https://github.com/paskal/terrty/blob/fee5512800/blog/docker-compose.yml#L52) your image for months and months. Could you please bump the version of Chrome inside the container? I'm having render issues and to be sure they are not related with the browser I need to make sure it's recent version, but last [image uploaded](https://hub.docker.com/r/pink33n/html-to-pdf/) is 1y old.

**Comment by pinkeen** [comment]
Hello, I've just tried bumping chrome to v70, but it crashes upon execution. I will investigate it later, but it might not be that straightforward.

**Comment by pinkeen** [comment]
Bumped and tagged with 70.0

**Comment by pinkeen** [comment]
BTW at the same time the NPM package has been bumped to 1.8.0 too
https://github.com/Szpadel/chrome-headless-render-pdf
